# BACKEND-PODS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-mongo-app
  template:
    metadata:
      labels:
        app: backend-mongo-app
    spec:
      containers:
        - name: backend-app
          image: localhost:5000/backend-app:v1
          ports:
            - containerPort: 5000
        - name: mongo
          image: localhost:5000/mongo:latest
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-storage
          emptyDir: {}
---
# BACKEND-SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend-mongo-app
  ports:
    - name: backend-app-port
      protocol: TCP
      #  the port that other services or clients can use to access the pods behind the service. It is the port number that is advertised by the service to the outside world.
      port: 5000
      #  the port number on the pod to which the traffic will be forwarded by the service. It represents the port on which the application inside the pod is listening and expects to receive traffic.
      targetPort: 5000
    - name: mongo-db-port
      protocol: TCP
      port: 27017
      targetPort: 27017
